version: '3.8'
services:
  reverse-proxy:
    image: huakunshen/nginx-certbot
    ports:
      - 7001:80
      - 7000:443
    restart: unless-stopped
    volumes:
      - ./config:/etc/nginx/sites-available
      - ./letsencrypt:/etc/letsencrypt
  octoprint-assistant:
    # image: huakunshen/octoprint-assistant:latest
    build: .
    restart: unless-stopped
    ports:
      - 7002:8000
    env_file:
      - .env
